---
# Patch existing namespace : add label
- name: add label to existing namespace
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Openshift-storage Namespace
      k8s:
        state: patch
        kind: service
        name: beer-native
        namespace: beer
        definition:
          spec:
            template:
              metadata:
                annotations:
                  autoscaling.knative.dev/maxScale: "20"
