kind: KafkaBridge
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: my-bridge
  namespace: namespace-placeholder
spec:
  replicas: 1
  bootstrapServers: 'my-cluster-kafka-bootstrap:9092'
  http:
    port: 8080

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dynatrace-prob-notify
  namespace: namespace-placeholder  
  labels:
    strimzi.io/cluster: my-cluster
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3
  topicName: ' dynatrace-prob-notify'
