apiVersion: v1
kind: Pod
metadata:
  name: att-rules
  namespace: namespace-placeholder
  labels:
    app: att-rules
spec:
      containers:
        - name: att-rules
          image: 'quay.io/intelli-infra-solution/att-rules-tmp:perf'
          ports:
            - containerPort: 8282

---

apiVersion: v1
kind: Service
metadata:
  name: att-rules
  namespace: namespace-placeholder
spec:
  ports:
    - protocol: TCP
      port: 8282
      targetPort: 8282
  selector:
    app: att-rules